// GENERATED by scripts/build-package.mjs from package.json. Do not edit: the build rewrites it, and packages/sdk/test/version.test.ts
// fails if it ever disagrees with package.json.
export const SDK_VERSION = '0.9.0';
