import { readFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { describe, expect, it } from 'vitest';
import { govRootV3FromPortable, verifyPortable, VerifyError } from '../src/index.js';

/**
 * The cross-language conformance suite, generated by certen-validator cmd/proofv2conformance and run there by
 * pkg/proof/v2 TestConformanceSuite. Both verifiers must reach the manifest's verdict on every case, and report the
 * manifest's values for the valid one, govRoot v3 included.
 */
const dir = new URL('./fixtures/proofv2/', import.meta.url);
const manifest = JSON.parse(readFileSync(new URL('manifest.json', dir), 'utf8'));
const base = gunzipSync(readFileSync(new URL(manifest.base, dir))).toString('utf8');

/** The certen:accval:v1 root of the valid case's spine-derived set: certen-validator pkg/accumulateset's golden for
 * the live Kermit proof, the root production V8.2 anchors committed. The manifest does not carry it. */
const GOLDEN_ACCUMULATE_SET_ROOT = 'afa6bd344b04b6ff9645c97b09254af9c25a214991e0b442538e9084d4136bf5';
/** pkg/intentcert's golden govRoot v3 for the same proof and inputs, which the manifest must carry exactly. */
const GOLDEN_GOVROOT_V3 = '0477ea2c8f1d2ad8d3a84a5dc3f87f241e57efc97688016f88cb4001521dcee2';

type Op = { path: (string | number)[]; set?: unknown; delete?: boolean; truncate?: number };

/** The same three operations as Go's proofv2.ApplyPatch. */
function applyPatch(doc: any, ops: Op[]): void {
  for (const op of ops ?? []) {
    let cur = doc;
    op.path.forEach((k, i) => {
      const last = i === op.path.length - 1;
      if (last) {
        if (op.delete) delete cur[k];
        else if (op.truncate !== undefined) cur[k] = cur[k].slice(0, op.truncate);
        else cur[k] = op.set;
      }
      cur = cur[k];
    });
  }
}

/** The report fields the manifest carries, as the Go suite builds them. */
function reported(doc: any) {
  const r = verifyPortable(doc);
  return {
    incarnation: r.incarnation,
    majors: r.majors,
    certifiedBlock: r.certifiedBlock,
    certifiedRoot: r.certifiedRoot,
    checkBlock: r.checkBlock,
    setVerdict: r.setVerdict,
    validators: r.validators,
    threshold: r.threshold,
    partition: r.partition,
    anchorBlock: r.anchorBlock,
    pages: r.pages.length,
    govRootV3: govRootV3FromPortable(r, doc).root,
  };
}

describe('proof v2 conformance', () => {
  it('has the format and cases the Go verifier runs', () => {
    expect(manifest.format).toBe('certen-proof-v2-accumulate-portable/1');
    expect(manifest.cases.length).toBeGreaterThanOrEqual(22);
  });

  for (const c of manifest.cases) {
    it(`${c.name}: ${c.expect}${c.attack ? ` (${c.attack})` : ''}`, () => {
      const doc = JSON.parse(base);
      applyPatch(doc, c.patch);
      if (c.expect === 'verified') {
        expect(reported(doc)).toEqual(c.report);
        expect(c.report.govRootV3).toBe(GOLDEN_GOVROOT_V3);
        expect(verifyPortable(doc).accumulateSetRoot).toBe(GOLDEN_ACCUMULATE_SET_ROOT);
      } else {
        expect(c.expect).toBe('refused');
        expect(() => verifyPortable(doc)).toThrow(VerifyError);
      }
    });
  }
});

/**
 * The manifest's additional documents: whole documents built from fixed keys (cmd/proofv2conformance/synthetic.go), the first
 * with a network update in its spine. The Go suite (TestConformanceSyntheticDocuments) runs the same files. The proof verifies,
 * the validator set is reported as asserted because it changed after genesis, and govRoot v3 refuses it with Go's message.
 */
describe('proof v2 conformance: whole documents with a network update', () => {
  it('lists at least one additional document', () => {
    expect(manifest.documents.length).toBeGreaterThanOrEqual(1);
  });

  for (const d of manifest.documents as any[]) {
    const text = gunzipSync(readFileSync(new URL(d.file, dir))).toString('utf8');

    it(`${d.name}: verifies, reports the update applied, and refuses govRoot v3 as Go does`, () => {
      const doc = JSON.parse(text);
      const r = verifyPortable(doc);
      const { govRootV3: _omitted, ...expected } = d.report;
      expect({
        incarnation: r.incarnation, majors: r.majors, certifiedBlock: r.certifiedBlock, certifiedRoot: r.certifiedRoot,
        checkBlock: r.checkBlock, setVerdict: r.setVerdict, validators: r.validators, threshold: r.threshold,
        partition: r.partition, anchorBlock: r.anchorBlock, pages: r.pages.length,
      }).toEqual(expected);
      expect(r.setVerdict).toBe('validator_set_asserted');
      expect(r.validators).toBe(4); // the genesis set had three
      expect(() => govRootV3FromPortable(r, doc)).toThrow(d.govRootRefusal.replace(/^govRoot v3: /, 'govRoot v3: '));
    });

    for (const c of d.cases) {
      it(`${d.name} / ${c.name}: refused (${c.attack})`, () => {
        const doc = JSON.parse(text);
        applyPatch(doc, c.patch);
        expect(() => verifyPortable(doc)).toThrow(VerifyError);
      });
    }
  }
});
