import { readFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { describe, expect, it } from 'vitest';
import { verifyPortable } from '../src/index.js';

/**
 * The cross-language conformance suite, generated by certen-validator cmd/proofv2conformance and run there by
 * pkg/proof/v2 TestConformanceSuite. Both verifiers must reach the manifest's verdict on every case, and report the
 * manifest's values for the valid one.
 */
const dir = new URL('./fixtures/proofv2/', import.meta.url);
const manifest = JSON.parse(readFileSync(new URL('manifest.json', dir), 'utf8'));
const base = gunzipSync(readFileSync(new URL(manifest.base, dir))).toString('utf8');

type Op = { path: (string | number)[]; set?: unknown; delete?: boolean; truncate?: number };

/** The same three operations as Go's proofv2.ApplyPatch. */
function applyPatch(doc: any, ops: Op[]): void {
  for (const op of ops ?? []) {
    let cur = doc;
    op.path.forEach((k, i) => {
      const last = i === op.path.length - 1;
      if (last) {
        if (op.delete) delete cur[k];
        else if (op.truncate !== undefined) cur[k] = cur[k].slice(0, op.truncate);
        else cur[k] = op.set;
      }
      cur = cur[k];
    });
  }
}

describe('proof v2 conformance', () => {
  it('has the format and cases the Go verifier runs', () => {
    expect(manifest.format).toBe('certen-proof-v2-accumulate-portable/1');
    expect(manifest.cases.length).toBeGreaterThanOrEqual(22);
  });

  for (const c of manifest.cases) {
    it(`${c.name}: ${c.expect}${c.attack ? ` (${c.attack})` : ''}`, () => {
      const doc = JSON.parse(base);
      applyPatch(doc, c.patch);
      if (c.expect === 'verified') {
        const r = verifyPortable(doc);
        const { pages, ...rest } = r;
        expect({ ...rest, pages: pages.length }).toEqual(c.report);
      } else {
        expect(() => verifyPortable(doc)).toThrow();
      }
    });
  }
});
