/**
 * Emit `llms-full.txt` — the full API digest for an agent building on CERTEN.
 *
 * Scoped to what the SDK can actually reach. The gateway exposes ~4x more operations than the SDK
 * wraps, and documenting all of them here would invite an agent to call `certen.billing.ledger()`,
 * which does not exist. Uncovered endpoints get named in a closing section instead, so the gap is
 * stated rather than implied.
 */
import { ERROR_CODES } from '../lib/errors.mjs';

const BULLET = '  - ';

function fieldLines(fields, indent = BULLET) {
  const out = [];
  for (const f of fields) {
    const req = f.required ? ' **required**' : '';
    const desc = f.description ? ` — ${f.description}` : '';
    out.push(`${indent}\`${f.name}\`: ${f.type}${req}${desc}`);
    for (const c of f.children ?? []) {
      const cdesc = c.description ? ` — ${c.description}` : '';
      out.push(`    ${indent}\`${c.name}\`: ${c.type}${cdesc}`);
    }
  }
  return out;
}

function operationBlock(op) {
  const L = [];
  L.push(`${op.method} ${op.path}${op.summary ? ` — ${op.summary}` : ''}`);
  if (op.scopes.length > 0) L.push(`Scope: ${op.scopes.map((s) => `\`${s}\``).join(', ')}`);
  if (op.description) L.push('', op.description);

  if (op.pathParams.length > 0) {
    L.push('', 'Path parameters:');
    L.push(...fieldLines(op.pathParams));
  }
  if (op.query.length > 0) {
    L.push('', 'Query parameters:');
    L.push(...fieldLines(op.query));
  }
  if (op.body.length > 0) {
    L.push('', 'Request body:');
    L.push(...fieldLines(op.body));
  }
  for (const r of op.responses) {
    const rdesc = r.description ? ` — ${r.description.replace(/[.:]$/, '')}` : '';
    L.push('', `Response ${r.code}${r.isArray ? ' (array)' : ''}${rdesc}:`);
    L.push(...fieldLines(r.fields));
  }
  return L.join('\n');
}

export function emitLlmsFull({ spec, ops, map, sdkVersion }) {
  const byId = new Map(ops.map((o) => [o.id, o]));
  const L = [];

  L.push('# CERTEN TypeScript SDK — full API digest');
  L.push('');
  L.push('> GENERATED by `tools/agentgen` from `spec/openapi.json`. Do not hand-edit — regenerate with');
  L.push('> `npm run agentgen`. Short version for getting started: `llms.txt`. Working ON the SDK: `AGENTS.md`.');
  L.push('');
  L.push(`Package: \`@certen.io/sdk\` v${sdkVersion}`);
  L.push(`Gateway: ${spec.info?.title} v${spec.info?.version}`);
  L.push('Default base URL: `https://gateway.kompendium.co` (override with `baseUrl` or `CERTEN_API_URL`)');
  L.push('');

  L.push('## Install');
  L.push('');
  L.push('```bash');
  L.push('npm install @certen.io/sdk');
  L.push('```');
  L.push('');
  L.push('```ts');
  L.push("import { CertenClient } from '@certen.io/sdk';");
  L.push('const certen = new CertenClient({ apiKey: process.env.CERTEN_API_KEY! });');
  L.push('```');
  L.push('');

  L.push('## Authentication');
  L.push('');
  L.push('Every request carries `X-API-Key`. The SDK sets it from `apiKey`. There is no other auth path');
  L.push('for SDK calls — OAuth2 (`/v1/oauth/token`) exists on the gateway for portal clients, not for this SDK.');
  L.push('');

  L.push('## Rules that decide whether your code works');
  L.push('');
  L.push('- **Your key never reaches the SDK.** You pass a `sign` function; the SDK hands it bytes and takes');
  L.push('  back a signature. Sign the RAW BYTES of the hex string — do not hash it again, do not sign the ASCII.');
  L.push('- **Every POST needs an Idempotency-Key.** The SDK adds one automatically. A network error is');
  L.push('  otherwise indistinguishable from success, and a blind retry opens a SECOND intent — on a value');
  L.push('  transfer that means paying twice.');
  L.push('- **A proof cycle takes 60–110 seconds.** Real validator work, not a tunable delay. `execute.wait()`');
  L.push('  defaults to a 360s budget. A 30-second timeout around it will simply always fire.');
  L.push('- **Identity creation is asynchronous.** `identity.create` returns `202` and provisioning continues.');
  L.push('  Poll `identity.get` until the status is terminal and `can_sign` is true before relying on it.');
  L.push('- **`vote` is `approve` | `reject` | `abstain`** — a lowercase string, not a number, and not `accept`.');
  L.push('  It is folded into the signature preimage, so it is fixed when signing data is created.');
  L.push('- **Amounts are base units as STRINGS.** A JSON number silently loses precision past 2^53.');
  L.push('- **Retry only the retryable codes below.** Every other code is a condition that will not change on');
  L.push('  its own, so retrying it just burns turns.');
  L.push('');

  L.push('## Error catalog');
  L.push('');
  L.push('Catch `CertenError` and branch on `.code`. `.isRetryable` implements the table below.');
  L.push('');
  L.push('| Code | HTTP | Retryable | Meaning | What to do |');
  L.push('|---|---|:--:|---|---|');
  for (const e of ERROR_CODES) {
    L.push(`| \`${e.code}\` | ${e.status || '—'} | ${e.retryable ? 'yes' : 'no'} | ${e.meaning} | ${e.fix} |`);
  }
  L.push('');

  L.push('## Methods');
  L.push('');
  for (const r of map) {
    L.push(`### certen.${r.resource}`);
    L.push('');
    for (const m of r.methods) {
      L.push(`#### certen.${r.resource}.${m.name}()`);
      L.push('');
      if (m.doc) {
        L.push(m.doc);
        L.push('');
      }
      if (m.calls.length > 1) {
        L.push(`Calls ${m.calls.length} endpoints in sequence:`);
        L.push('');
      }
      for (const call of m.calls) {
        const op = byId.get(call.id);
        if (!op) continue;
        L.push(operationBlock(op));
        L.push('');
      }
    }
  }

  const covered = new Set();
  for (const r of map) for (const m of r.methods) for (const c of m.calls) covered.add(c.id);
  const uncovered = ops.filter((o) => !covered.has(o.id));

  L.push('## Gateway endpoints with no SDK method');
  L.push('');
  L.push(`The SDK wraps ${covered.size} of the gateway's ${ops.length} operations. The rest are reachable only by`);
  L.push('raw HTTP against the same base URL and `X-API-Key`. **There is no SDK method for these — do not invent one.**');
  L.push('');
  const byTag = new Map();
  for (const o of uncovered) {
    if (!byTag.has(o.tag)) byTag.set(o.tag, []);
    byTag.get(o.tag).push(o);
  }
  for (const [tag, list] of [...byTag].sort((a, b) => a[0].localeCompare(b[0]))) {
    L.push(`**${tag}**`);
    for (const o of list) L.push(`${BULLET}\`${o.method} ${o.path}\`${o.summary ? ` — ${o.summary}` : ''}`);
    L.push('');
  }

  return `${L.join('\n').replace(/\n{3,}/g, '\n\n')}\n`;
}
