// GENERATED by tools/agentgen/emit/mcp-output-schemas.mjs from spec/openapi.json and packages/mcp/src/tools.ts. Do not edit.
// `npm run agentgen` rewrites it and `npm run agentgen:check` fails CI when it is stale.
// Tools whose result the tool builds itself (8) have hand-written schemas in output-schemas.ts.

export const GENERATED_OUTPUT_SCHEMAS: Readonly<Record<string, Readonly<Record<string, unknown>>>> = {
  "certen_admin_audit_log": {
    "description": "Audit log entries with pagination metadata.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "entries": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "pagination": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "limit": {
            "type": "number"
          },
          "offset": {
            "type": "number"
          },
          "total": {
            "type": "number"
          },
          "has_more": {
            "type": "boolean"
          }
        }
      }
    }
  },
  "certen_admin_list_api_keys": {
    "description": "API keys for the org.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "api_keys": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "prefix": {
              "type": "string"
            },
            "org_id": {
              "type": "string"
            },
            "permissions": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "rate_limit_rpm": {
              "type": [
                "number",
                "null"
              ]
            },
            "is_active": {
              "type": "boolean"
            },
            "created_at": {
              "type": "string"
            },
            "expires_at": {
              "type": [
                "string",
                "null"
              ]
            },
            "last_used_at": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      }
    }
  },
  "certen_admin_rotate_api_key": {
    "description": "Key rotated; new raw key returned once.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "previous_id": {
        "type": "string"
      },
      "new_key": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "id": {
            "type": "string"
          },
          "key": {
            "type": "string"
          },
          "prefix": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "rate_limit_rpm": {
            "type": [
              "number",
              "null"
            ]
          },
          "permissions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "created_at": {
            "type": "string"
          }
        }
      },
      "warning": {
        "type": "string"
      }
    }
  },
  "certen_admin_usage": {
    "description": "Usage summary for the requested period.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "period": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "from": {
            "type": "string"
          },
          "to": {
            "type": "string"
          }
        }
      },
      "total_requests": {
        "type": "number"
      },
      "successful_requests": {
        "type": "number"
      },
      "by_endpoint": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "endpoint": {
              "type": "string"
            },
            "count": {
              "type": "number"
            }
          }
        }
      },
      "daily": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "date": {
              "type": "string"
            },
            "count": {
              "type": "number"
            }
          }
        }
      }
    }
  },
  "certen_billing_balance": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "currency": {
        "type": "string"
      },
      "available_usd": {
        "type": "string"
      },
      "held_usd": {
        "type": "string"
      },
      "credit_limit_usd": {
        "type": "string"
      },
      "spendable_usd": {
        "type": "string"
      },
      "remaining_usd": {
        "type": "string"
      },
      "pending_intents": {
        "type": "integer"
      },
      "uncovered_usd": {
        "type": "string"
      },
      "status": {
        "type": "string",
        "enum": [
          "active",
          "suspended",
          "closed"
        ]
      },
      "suspended_reason": {
        "type": [
          "string",
          "null"
        ]
      },
      "enforcing": {
        "type": "boolean"
      },
      "credit": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "kind": {
            "type": "string",
            "enum": [
              "none",
              "trial",
              "comp",
              "terms"
            ]
          },
          "label": {
            "type": [
              "string",
              "null"
            ]
          },
          "granted_limit_usd": {
            "type": "string"
          },
          "expires_at": {
            "type": [
              "string",
              "null"
            ]
          },
          "expired": {
            "type": "boolean"
          },
          "warns_at_usd": {
            "type": "string"
          },
          "suspends_at_usd": {
            "type": "string"
          }
        }
      }
    }
  },
  "certen_billing_ledger": {
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "entries": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "id": {
              "type": "string"
            },
            "account": {
              "type": "string"
            },
            "amount_usd": {
              "type": "string"
            },
            "kind": {
              "type": "string"
            },
            "ref_type": {
              "type": [
                "string",
                "null"
              ]
            },
            "ref_id": {
              "type": [
                "string",
                "null"
              ]
            },
            "memo": {
              "type": [
                "string",
                "null"
              ]
            },
            "created_at": {
              "type": "string"
            }
          }
        }
      },
      "pagination": {
        "type": "object",
        "additionalProperties": true,
        "description": "Where this page sits. Loop until `has_more` is false — do NOT infer the end from a short page, which ends early whenever a page lands exactly on the page size.",
        "properties": {
          "limit": {
            "type": "integer",
            "description": "Page size that was applied."
          },
          "offset": {
            "type": "integer",
            "description": "Where this page started."
          },
          "has_more": {
            "type": "boolean",
            "description": "True when at least one further row exists. The only field a pager needs."
          },
          "returned": {
            "type": "integer",
            "description": "Rows in this page."
          }
        }
      }
    }
  },
  "certen_billing_obligations": {
    "type": "object",
    "additionalProperties": true
  },
  "certen_billing_payer_addresses": {
    "type": "object",
    "additionalProperties": true
  },
  "certen_billing_receipt": {
    "type": "object",
    "additionalProperties": true
  },
  "certen_billing_receipts": {
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "receipts": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "id": {
              "type": "string"
            },
            "receipt_number": {
              "type": "string",
              "description": "Monotonic per org. A STRING: it can exceed 2^53."
            },
            "type": {
              "type": "string",
              "description": "charge | payment | refund | adjustment."
            },
            "amount_usd": {
              "type": "string"
            },
            "currency": {
              "type": "string"
            },
            "ref_type": {
              "type": [
                "string",
                "null"
              ]
            },
            "ref_id": {
              "type": [
                "string",
                "null"
              ]
            },
            "digest": {
              "type": "string"
            },
            "signed": {
              "type": "boolean",
              "description": "Whether an ed25519 signature exists."
            },
            "logged": {
              "type": "boolean",
              "description": "Whether it is in the transparency log. An inclusion proof exists only for these — asking for one otherwise returns 404."
            },
            "issued_at": {}
          }
        }
      },
      "pagination": {
        "type": "object",
        "additionalProperties": true,
        "description": "Where this page sits. Loop until `has_more` is false — do NOT infer the end from a short page, which ends early whenever a page lands exactly on the page size.",
        "properties": {
          "limit": {
            "type": "integer",
            "description": "Page size that was applied."
          },
          "offset": {
            "type": "integer",
            "description": "Where this page started."
          },
          "has_more": {
            "type": "boolean",
            "description": "True when at least one further row exists. The only field a pager needs."
          },
          "returned": {
            "type": "integer",
            "description": "Rows in this page."
          }
        }
      }
    }
  },
  "certen_billing_register_payer": {
    "type": "object",
    "additionalProperties": true
  },
  "certen_billing_verification_keys": {
    "type": "object",
    "additionalProperties": true
  },
  "certen_chains_list": {
    "type": "object",
    "additionalProperties": true
  },
  "certen_errors": {
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "errors": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "code": {
              "type": "string"
            },
            "status": {
              "type": "integer"
            },
            "meaning": {
              "type": "string"
            },
            "retryable": {
              "type": "boolean"
            },
            "audience": {
              "type": "string",
              "enum": [
                "caller",
                "platform"
              ],
              "description": "`platform` means nothing the caller can change."
            },
            "action": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "certen_execute_wait": {
    "description": "The transaction intent, including a joined `proof` object when delivered and proven.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "intent_id": {
        "type": "string"
      },
      "identity_id": {
        "type": "string"
      },
      "status": {
        "type": "string",
        "description": "Where the intent is: `created`, `signing_required`, `submitted`, `processing`, `anchoring` (in flight); `executed` - the action EXECUTED on its chain and its proof bundle is pending; CERTEN produces it automatically, the fee is held meanwhile, and the intent then reads `completed`. Not a failure. `completed` (executed and proven); `completed_unproven` - executed, and its proof can never be produced (declared by an operator with the evidence; billed gas only, fee waived); `failed`; `expired`."
      },
      "intent_type": {
        "type": "string"
      },
      "completion_basis": {
        "type": [
          "string",
          "null"
        ],
        "enum": [
          "proof_artifact",
          "execution_observed",
          "chain_receipt",
          null
        ],
        "description": "What completion rested on. `proof_artifact`: the validators produced an indexed proof (`proof_id`). `execution_observed`: the gateway observed the destination-chain settlement; for a contract call it also read the settlement receipt and found every committed `expectedEvents` entry. A contract call whose committed events are absent never completes: it fails with `reason_code` `expectation_unmet` (or `expectation_unverifiable` when the receipt could not be read in time). Receipts are read on EVM chains only: a contract call whose legs are all on non-EVM chains completes on observed execution with `completion_evidence.expected_events.verified: false` (`reason: non_evm_receipts_not_supported`), and in a mixed intent only the EVM legs are checked. `chain_receipt` appears only on legacy rows. Null until the intent completes."
      },
      "accum_tx_hash": {
        "type": [
          "string",
          "null"
        ]
      },
      "proof_lookup": {
        "type": "object",
        "description": "Present when this read looked the proof id up because it was not yet recorded: `resolved` (proof_id carries it), `not_found` (not anchored yet - poll again), or `unavailable` (the proof service failed to answer, with its HTTP status, null when unreachable, and reason). A null proof_id with `unavailable` is NOT \"not anchored yet\".",
        "additionalProperties": false,
        "properties": {
          "state": {
            "type": "string",
            "enum": [
              "resolved",
              "not_found",
              "unavailable"
            ]
          },
          "status": {
            "type": [
              "integer",
              "null"
            ]
          },
          "reason": {
            "type": "string"
          }
        }
      },
      "proof_id": {
        "type": [
          "string",
          "null"
        ],
        "description": "The CERTEN proof artifact for this transaction. Feed it to POST /v1/proof/{id}/share to mint a link a counterparty can resolve without a CERTEN account. An intent completes only on the verdict of the validators, with its proof (RB5-F39), so a `completed` intent carries it. It is null while the intent is in flight, and while it is `executed` with its proof bundle still pending. This endpoint resolves it from the proof service on read. An intent on several chains has one proof per chain member: it completes only when every chain names its own proof and none of them records a revert, this is its first declared chain's, and `proofs` lists every one with the legs it settles."
      },
      "proof_bundle_url": {
        "type": [
          "string",
          "null"
        ]
      },
      "proofs": {
        "type": "array",
        "description": "Every chain member's proof, as the validators recorded it: one per chain an intent settles on (a single-chain intent has one), each with its own bundle link. For an intent on several chains, in the order it declares them, each with `legs`. Empty until the validators have produced one.",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "chain_id": {
              "type": "integer"
            },
            "legs": {
              "type": "array",
              "items": {
                "type": "integer"
              },
              "description": "Present for an intent on several chains: the indices of its request legs on this chain, which share this chain's proof. Empty for a chain the intent does not declare."
            },
            "proof_id": {
              "type": "string"
            },
            "proof_bundle_url": {
              "type": [
                "string",
                "null"
              ]
            },
            "write_back_tx": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      },
      "validator": {
        "type": [
          "object",
          "null"
        ],
        "description": "What the CERTEN validators recorded for this intent, followed until it is final - also after the gateway has ended the intent. Null until first observed.",
        "additionalProperties": false,
        "properties": {
          "state": {
            "type": "string",
            "enum": [
              "not_discovered",
              "in_progress",
              "awaiting_signatures",
              "settling",
              "settled",
              "refused",
              "failed",
              "unavailable",
              "executed_proof_pending",
              "executed_proof_unavailable"
            ]
          },
          "since": {},
          "overdue": {
            "type": "boolean",
            "description": "Delivered on Accumulate and not discovered by the validators within VALIDATOR_DISCOVERY_OVERDUE_MIN."
          },
          "members": {
            "type": [
              "array",
              "null"
            ],
            "description": "Every chain member, each with its own settlement, write-back and proof. Null when the validators reported none.",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "chain_id": {
                  "type": "integer"
                },
                "recorded": {
                  "type": "boolean"
                },
                "settlement": {
                  "type": [
                    "string",
                    "null"
                  ],
                  "enum": [
                    "settled",
                    "reverted",
                    "unobserved",
                    "none",
                    null
                  ]
                },
                "proof_cycle": {
                  "type": [
                    "string",
                    "null"
                  ],
                  "enum": [
                    "written",
                    "failed",
                    "proof_pending",
                    "proof_unavailable",
                    "refused",
                    null
                  ]
                },
                "settlement_tx": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "write_back_tx": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "proof_id": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "proof_bundle_url": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "effects_proven": {
                  "type": [
                    "boolean",
                    "null"
                  ]
                }
              }
            }
          },
          "disagreement": {
            "type": [
              "object",
              "null"
            ],
            "description": "When the validators' final outcome contradicts how the gateway ended the intent: what differs, and since when. Null while they agree or the validators have not finished.",
            "additionalProperties": false,
            "properties": {
              "what": {
                "type": "string"
              },
              "since": {}
            }
          }
        }
      },
      "error_message": {
        "type": [
          "string",
          "null"
        ]
      },
      "reason_code": {
        "type": [
          "string",
          "null"
        ],
        "description": "Why the intent ended where it did, as a stable value rather than prose. `target_reverted` is the one to branch on: CERTEN validated, proved, anchored and submitted, and the DESTINATION CONTRACT rejected the call. That is a business outcome — it is billed, and retrying the identical call reverts again. `validator_refused`: the validators refused the intent itself (it cannot be settled as written, no entitlement, or its governance fell short); nothing executed. `validator_unprocessed`, `chain_settlement_failed`, `validator_failed_unclassified`, `post_submission_timeout`, `network_failed`, `pre_submission_error`, `relayer_exhausted`, `expectation_unmet`, `expectation_unverifiable`: CERTEN did not complete. `execution_proof_unavailable` (status `completed_unproven`): the action executed, and its proof can never be produced. Null when the intent has not ended, or ended without a recorded reason. `expired` means the `expires_at` deadline passed before every required authority signed; nothing executed and nothing is charged. A deadline-derived `expired` on a submitted transaction is re-checked for INTENT_EXPIRY_RECHECK_HOURS and reopened if Accumulate reports it delivered after all."
      },
      "additional_authorities": {
        "type": [
          "array",
          "null"
        ],
        "items": {
          "type": "string"
        },
        "description": "Transaction-header additional authorities the intent was created with; null when none."
      },
      "expires_at": {
        "type": [
          "string",
          "null"
        ],
        "description": "Transaction-header deadline (RFC 3339, whole seconds); null when the intent never expires."
      },
      "created_at": {},
      "updated_at": {},
      "completed_at": {},
      "proof": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "id": {
            "type": "string"
          },
          "bundle_url": {
            "type": [
              "string",
              "null"
            ]
          },
          "layers": {},
          "governance": {},
          "attestations": {},
          "parts": {
            "type": "object",
            "description": "Per part, what the proof service answered: `present`, `absent` (it holds none - its 404) or `unavailable` (it failed to answer; the part is null because it is not known, never because it is empty). RB4-F40.",
            "additionalProperties": false,
            "properties": {
              "layers": {
                "type": "string",
                "enum": [
                  "present",
                  "absent",
                  "unavailable"
                ]
              },
              "governance": {
                "type": "string",
                "enum": [
                  "present",
                  "absent",
                  "unavailable"
                ]
              },
              "attestations": {
                "type": "string",
                "enum": [
                  "present",
                  "absent",
                  "unavailable"
                ]
              }
            }
          },
          "unavailable": {
            "type": "array",
            "description": "Each part the proof service failed to answer for, with its HTTP status (null when it could not be reached) and reason. Empty when every part was answered.",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "part": {
                  "type": "string"
                },
                "status": {
                  "type": [
                    "integer",
                    "null"
                  ]
                },
                "reason": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "outcome": {
        "type": "object",
        "description": "The named state of the action itself: completed, completed_unproven, executed, failed, pending or unknown.",
        "properties": {
          "status": {
            "type": "string",
            "description": "The gateway's status, verbatim."
          },
          "class": {
            "type": "string",
            "enum": [
              "in_flight",
              "executed",
              "terminal_success",
              "terminal_gas_only",
              "terminal_failure",
              "unknown"
            ]
          },
          "terminal": {
            "type": "boolean"
          },
          "outcome": {
            "type": "string",
            "enum": [
              "completed",
              "completed_unproven",
              "executed",
              "failed",
              "pending",
              "unknown"
            ]
          },
          "reason": {
            "type": [
              "string",
              "null"
            ],
            "description": "For completed_unproven always execution_proof_unavailable; for a failure the gateway reason_code."
          }
        },
        "required": [
          "status",
          "class",
          "terminal",
          "outcome",
          "reason"
        ],
        "additionalProperties": false
      }
    },
    "required": [
      "outcome"
    ]
  },
  "certen_governance_get": {
    "description": "Governance operation status and details.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "governance_op_id": {
        "type": "string"
      },
      "identity_id": {
        "type": "string"
      },
      "operation_type": {
        "type": "string"
      },
      "status": {
        "type": "string"
      },
      "request_payload": {
        "type": "object",
        "additionalProperties": true
      },
      "signing_data": {
        "type": [
          "object",
          "null"
        ],
        "additionalProperties": true
      },
      "accum_tx_hash": {
        "type": [
          "string",
          "null"
        ]
      },
      "created_at": {
        "type": "string"
      },
      "completed_at": {
        "type": [
          "string",
          "null"
        ]
      }
    }
  },
  "certen_governance_submit_signature": {
    "description": "Signature accepted and governance operation submitted to the network.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "governance_op_id": {
        "type": "string"
      },
      "status": {
        "type": "string"
      },
      "tx_hash": {
        "type": "string"
      }
    }
  },
  "certen_identity_get": {
    "description": "The identity plus any requested enrichments (governance, balances, pending).",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "id": {
        "type": "string"
      },
      "adi_url": {
        "type": "string"
      },
      "book_url": {
        "type": [
          "string",
          "null"
        ]
      },
      "key_page_url": {
        "type": [
          "string",
          "null"
        ]
      },
      "status": {
        "type": "string",
        "description": "provisioning | active | error. Creation is async — poll until terminal."
      },
      "can_sign": {
        "type": [
          "boolean",
          "null"
        ],
        "description": "False when an external-mode identity has no stored public key — it can never sign, and every POST /v1/sign for it will fail. Null means the on-chain key page could not be read: treat it as \"do not proceed\", never as a soft yes. Check this before building on the identity. Repairable with PATCH /v1/identity/{id} { public_key } if the hash matches."
      },
      "error_message": {
        "type": [
          "string",
          "null"
        ],
        "description": "Why provisioning failed, when status is \"error\"."
      },
      "credit_balance": {
        "type": "number",
        "description": "Accumulate credits on the identity's key page (its creditBalance / 100: Accumulate keeps credits to two decimals). Read live from the key page when `credit_balance_source` is `key_page`; when that read failed it is the balance read when provisioning finished (`recorded`). RB4-F44."
      },
      "credit_balance_source": {
        "type": "string",
        "enum": [
          "key_page",
          "recorded"
        ]
      },
      "chain_accounts": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "created_at": {},
      "signing_mode": {
        "type": "string"
      },
      "signing_provider": {
        "type": "object",
        "additionalProperties": true
      },
      "governance": {
        "type": "object",
        "additionalProperties": true
      },
      "balances": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "pending": {
        "type": "object",
        "additionalProperties": true
      }
    }
  },
  "certen_identity_retire": {
    "description": "The identity was retired. Its quota slot is now free; the on-chain ADI is unaffected.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "deleted": {
        "type": "boolean"
      },
      "id": {
        "type": "string"
      },
      "adi_url": {
        "type": "string"
      },
      "note": {
        "type": "string"
      }
    }
  },
  "certen_identity_update": {
    "description": "The updated identity, re-fetched with default enrichments (same shape as GET /v1/identity/:id).",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "id": {
        "type": "string"
      },
      "adi_url": {
        "type": "string"
      },
      "book_url": {
        "type": [
          "string",
          "null"
        ]
      },
      "key_page_url": {
        "type": [
          "string",
          "null"
        ]
      },
      "status": {
        "type": "string",
        "description": "provisioning | active | error. Creation is async — poll until terminal."
      },
      "can_sign": {
        "type": [
          "boolean",
          "null"
        ],
        "description": "False when an external-mode identity has no stored public key — it can never sign, and every POST /v1/sign for it will fail. Null means the on-chain key page could not be read: treat it as \"do not proceed\", never as a soft yes. Check this before building on the identity. Repairable with PATCH /v1/identity/{id} { public_key } if the hash matches."
      },
      "error_message": {
        "type": [
          "string",
          "null"
        ],
        "description": "Why provisioning failed, when status is \"error\"."
      },
      "credit_balance": {
        "type": "number",
        "description": "Accumulate credits on the identity's key page (its creditBalance / 100: Accumulate keeps credits to two decimals). Read live from the key page when `credit_balance_source` is `key_page`; when that read failed it is the balance read when provisioning finished (`recorded`). RB4-F44."
      },
      "credit_balance_source": {
        "type": "string",
        "enum": [
          "key_page",
          "recorded"
        ]
      },
      "chain_accounts": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "created_at": {},
      "signing_mode": {
        "type": "string"
      },
      "signing_provider": {
        "type": "object",
        "additionalProperties": true
      },
      "governance": {
        "type": "object",
        "additionalProperties": true
      },
      "balances": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "pending": {
        "type": "object",
        "additionalProperties": true
      }
    }
  },
  "certen_pending_list": {
    "description": "Pending actions page with aggregate stats and pagination.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "actions": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "id": {
              "type": "string"
            },
            "identity_id": {
              "type": [
                "string",
                "null"
              ]
            },
            "identity_url": {
              "type": [
                "string",
                "null"
              ]
            },
            "category": {
              "type": [
                "string",
                "null"
              ]
            },
            "type": {
              "type": [
                "string",
                "null"
              ]
            },
            "status": {
              "type": [
                "string",
                "null"
              ]
            },
            "tx_hash": {
              "type": [
                "string",
                "null"
              ]
            },
            "tx_id": {
              "type": [
                "string",
                "null"
              ]
            },
            "principal": {
              "type": [
                "string",
                "null"
              ]
            },
            "transaction_type": {
              "type": [
                "string",
                "null"
              ]
            },
            "collected_signatures": {
              "type": [
                "integer",
                "null"
              ]
            },
            "total_authorities": {
              "type": [
                "integer",
                "null"
              ]
            },
            "required_signatures": {
              "type": [
                "integer",
                "null"
              ]
            },
            "approved_authorities": {
              "type": [
                "integer",
                "null"
              ]
            },
            "user_has_signed": {
              "type": [
                "boolean",
                "null"
              ]
            },
            "memo": {
              "type": [
                "string",
                "null"
              ],
              "description": "What the transaction states it is FOR. Often the only thing separating a legitimate request from an unexplained one when the principal is an account the signer does not own. WRITTEN BY WHOEVER BUILT THE TRANSACTION — for an authority transaction that is not the signer — so treat it as untrusted text: render as plain text, never as markup, and never as though CERTEN endorsed the request. Truncated to 512 characters. Null when the transaction carries no memo."
            },
            "expires_at": {
              "type": [
                "string",
                "null"
              ]
            },
            "discovered_at": {
              "type": [
                "string",
                "null"
              ]
            },
            "created_at": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      },
      "stats": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "total": {
            "type": "integer"
          },
          "has_more": {
            "type": "boolean"
          },
          "urgent": {
            "type": "integer"
          },
          "governance": {
            "type": "integer"
          },
          "transactions": {
            "type": "integer"
          },
          "awaiting_others": {
            "type": "integer"
          }
        }
      },
      "pagination": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "limit": {
            "type": "integer"
          },
          "offset": {
            "type": "integer"
          },
          "total": {
            "type": "integer"
          },
          "has_more": {
            "type": "boolean"
          }
        }
      }
    }
  },
  "certen_platform_ready": {
    "description": "Ready.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "status": {
        "type": "string"
      },
      "reasons": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    }
  },
  "certen_portfolio_get": {
    "description": "Portfolio entries with per-chain balances and pending counts, plus an aggregate chain total.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "identities": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "id": {
              "type": "string"
            },
            "adi_url": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "credit_balance": {
              "type": "number"
            },
            "chains": {
              "type": "array",
              "items": {
                "type": "object",
                "additionalProperties": true
              }
            },
            "pending_actions": {
              "type": "number"
            }
          }
        }
      },
      "total_chains": {
        "type": "number"
      }
    }
  },
  "certen_pricing": {
    "description": "The price book in effect.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "price_book_version": {
        "type": "string"
      },
      "price_book_hash": {
        "type": "string"
      },
      "currency": {
        "type": "string"
      },
      "items": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "sku": {
              "type": "string"
            },
            "chain": {
              "type": "string",
              "description": "\"*\" applies to any chain without its own entry."
            },
            "mode": {
              "type": "string",
              "description": "flat | quoted"
            },
            "platform_fee_usd": {
              "type": "string"
            },
            "gas_buffer_bps": {
              "type": "number"
            },
            "min_charge_usd": {
              "type": "string"
            },
            "max_charge_usd": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      }
    }
  },
  "certen_proof_open_shared": {
    "type": "object",
    "additionalProperties": true
  },
  "certen_proof_receipt": {
    "description": "Chain receipt for the transaction.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "tx_hash": {
        "type": "string"
      },
      "status": {
        "type": "string"
      },
      "principal": {
        "type": [
          "string",
          "null"
        ]
      },
      "tx_type": {
        "type": [
          "string",
          "null"
        ]
      },
      "anchored": {
        "type": "boolean"
      },
      "chain_index": {
        "type": [
          "integer",
          "null"
        ]
      },
      "block_time": {
        "type": [
          "string",
          "null"
        ]
      },
      "receipt": {
        "type": [
          "object",
          "null"
        ],
        "additionalProperties": true
      }
    }
  },
  "certen_quote": {
    "type": "object",
    "additionalProperties": true
  },
  "certen_quote_get": {
    "type": "object",
    "additionalProperties": true
  },
  "certen_scopes": {
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "scopes": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "audience": {
              "type": "string",
              "enum": [
                "customer",
                "operator"
              ],
              "description": "Operator scopes are for the fee console and platform staff."
            },
            "operations": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "description": "Operations requiring this scope, as `METHOD /path`."
            }
          }
        }
      }
    }
  },
  "certen_sign_create": {
    "description": "Sign request created. Provider mode returns `{status: \"signed\", tx_hash, signature_count, signing_mode: \"provider\"}`; external mode returns `{sign_request_id, status: \"signing_required\", signing_data, submit_url, expires_at}`.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "status": {
        "type": "string"
      },
      "tx_hash": {
        "type": "string"
      },
      "signature_count": {
        "type": "integer"
      },
      "signing_mode": {
        "type": "string",
        "enum": [
          "provider"
        ]
      },
      "sign_request_id": {
        "type": "string"
      },
      "signing_data": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "data_for_signature": {
            "type": "string"
          },
          "transaction_hash": {
            "type": "string"
          },
          "signer_url": {
            "type": "string"
          },
          "signer_version": {
            "type": "integer"
          },
          "timestamp": {
            "type": "integer"
          }
        }
      },
      "submit_url": {
        "type": "string"
      },
      "expires_at": {},
      "signing": {
        "type": "object",
        "additionalProperties": true
      },
      "signing_check": {
        "type": "object",
        "properties": {
          "ok": {
            "type": "boolean",
            "enum": [
              false
            ]
          },
          "code": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "details": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "required": [
          "ok",
          "code",
          "message"
        ],
        "additionalProperties": false
      }
    },
    "required": []
  },
  "certen_sign_submit_signature": {
    "description": "Signature accepted and the vote was relayed to Accumulate.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "status": {
        "type": "string"
      },
      "tx_hash": {
        "type": "string"
      },
      "signature_count": {
        "type": "integer"
      }
    }
  },
  "certen_transaction_get": {
    "description": "The transaction intent, including a joined `proof` object when delivered and proven.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "intent_id": {
        "type": "string"
      },
      "identity_id": {
        "type": "string"
      },
      "status": {
        "type": "string",
        "description": "Where the intent is: `created`, `signing_required`, `submitted`, `processing`, `anchoring` (in flight); `executed` - the action EXECUTED on its chain and its proof bundle is pending; CERTEN produces it automatically, the fee is held meanwhile, and the intent then reads `completed`. Not a failure. `completed` (executed and proven); `completed_unproven` - executed, and its proof can never be produced (declared by an operator with the evidence; billed gas only, fee waived); `failed`; `expired`."
      },
      "intent_type": {
        "type": "string"
      },
      "completion_basis": {
        "type": [
          "string",
          "null"
        ],
        "enum": [
          "proof_artifact",
          "execution_observed",
          "chain_receipt",
          null
        ],
        "description": "What completion rested on. `proof_artifact`: the validators produced an indexed proof (`proof_id`). `execution_observed`: the gateway observed the destination-chain settlement; for a contract call it also read the settlement receipt and found every committed `expectedEvents` entry. A contract call whose committed events are absent never completes: it fails with `reason_code` `expectation_unmet` (or `expectation_unverifiable` when the receipt could not be read in time). Receipts are read on EVM chains only: a contract call whose legs are all on non-EVM chains completes on observed execution with `completion_evidence.expected_events.verified: false` (`reason: non_evm_receipts_not_supported`), and in a mixed intent only the EVM legs are checked. `chain_receipt` appears only on legacy rows. Null until the intent completes."
      },
      "accum_tx_hash": {
        "type": [
          "string",
          "null"
        ]
      },
      "proof_lookup": {
        "type": "object",
        "description": "Present when this read looked the proof id up because it was not yet recorded: `resolved` (proof_id carries it), `not_found` (not anchored yet - poll again), or `unavailable` (the proof service failed to answer, with its HTTP status, null when unreachable, and reason). A null proof_id with `unavailable` is NOT \"not anchored yet\".",
        "additionalProperties": false,
        "properties": {
          "state": {
            "type": "string",
            "enum": [
              "resolved",
              "not_found",
              "unavailable"
            ]
          },
          "status": {
            "type": [
              "integer",
              "null"
            ]
          },
          "reason": {
            "type": "string"
          }
        }
      },
      "proof_id": {
        "type": [
          "string",
          "null"
        ],
        "description": "The CERTEN proof artifact for this transaction. Feed it to POST /v1/proof/{id}/share to mint a link a counterparty can resolve without a CERTEN account. An intent completes only on the verdict of the validators, with its proof (RB5-F39), so a `completed` intent carries it. It is null while the intent is in flight, and while it is `executed` with its proof bundle still pending. This endpoint resolves it from the proof service on read. An intent on several chains has one proof per chain member: it completes only when every chain names its own proof and none of them records a revert, this is its first declared chain's, and `proofs` lists every one with the legs it settles."
      },
      "proof_bundle_url": {
        "type": [
          "string",
          "null"
        ]
      },
      "proofs": {
        "type": "array",
        "description": "Every chain member's proof, as the validators recorded it: one per chain an intent settles on (a single-chain intent has one), each with its own bundle link. For an intent on several chains, in the order it declares them, each with `legs`. Empty until the validators have produced one.",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "chain_id": {
              "type": "integer"
            },
            "legs": {
              "type": "array",
              "items": {
                "type": "integer"
              },
              "description": "Present for an intent on several chains: the indices of its request legs on this chain, which share this chain's proof. Empty for a chain the intent does not declare."
            },
            "proof_id": {
              "type": "string"
            },
            "proof_bundle_url": {
              "type": [
                "string",
                "null"
              ]
            },
            "write_back_tx": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      },
      "validator": {
        "type": [
          "object",
          "null"
        ],
        "description": "What the CERTEN validators recorded for this intent, followed until it is final - also after the gateway has ended the intent. Null until first observed.",
        "additionalProperties": false,
        "properties": {
          "state": {
            "type": "string",
            "enum": [
              "not_discovered",
              "in_progress",
              "awaiting_signatures",
              "settling",
              "settled",
              "refused",
              "failed",
              "unavailable",
              "executed_proof_pending",
              "executed_proof_unavailable"
            ]
          },
          "since": {},
          "overdue": {
            "type": "boolean",
            "description": "Delivered on Accumulate and not discovered by the validators within VALIDATOR_DISCOVERY_OVERDUE_MIN."
          },
          "members": {
            "type": [
              "array",
              "null"
            ],
            "description": "Every chain member, each with its own settlement, write-back and proof. Null when the validators reported none.",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "chain_id": {
                  "type": "integer"
                },
                "recorded": {
                  "type": "boolean"
                },
                "settlement": {
                  "type": [
                    "string",
                    "null"
                  ],
                  "enum": [
                    "settled",
                    "reverted",
                    "unobserved",
                    "none",
                    null
                  ]
                },
                "proof_cycle": {
                  "type": [
                    "string",
                    "null"
                  ],
                  "enum": [
                    "written",
                    "failed",
                    "proof_pending",
                    "proof_unavailable",
                    "refused",
                    null
                  ]
                },
                "settlement_tx": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "write_back_tx": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "proof_id": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "proof_bundle_url": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "effects_proven": {
                  "type": [
                    "boolean",
                    "null"
                  ]
                }
              }
            }
          },
          "disagreement": {
            "type": [
              "object",
              "null"
            ],
            "description": "When the validators' final outcome contradicts how the gateway ended the intent: what differs, and since when. Null while they agree or the validators have not finished.",
            "additionalProperties": false,
            "properties": {
              "what": {
                "type": "string"
              },
              "since": {}
            }
          }
        }
      },
      "error_message": {
        "type": [
          "string",
          "null"
        ]
      },
      "reason_code": {
        "type": [
          "string",
          "null"
        ],
        "description": "Why the intent ended where it did, as a stable value rather than prose. `target_reverted` is the one to branch on: CERTEN validated, proved, anchored and submitted, and the DESTINATION CONTRACT rejected the call. That is a business outcome — it is billed, and retrying the identical call reverts again. `validator_refused`: the validators refused the intent itself (it cannot be settled as written, no entitlement, or its governance fell short); nothing executed. `validator_unprocessed`, `chain_settlement_failed`, `validator_failed_unclassified`, `post_submission_timeout`, `network_failed`, `pre_submission_error`, `relayer_exhausted`, `expectation_unmet`, `expectation_unverifiable`: CERTEN did not complete. `execution_proof_unavailable` (status `completed_unproven`): the action executed, and its proof can never be produced. Null when the intent has not ended, or ended without a recorded reason. `expired` means the `expires_at` deadline passed before every required authority signed; nothing executed and nothing is charged. A deadline-derived `expired` on a submitted transaction is re-checked for INTENT_EXPIRY_RECHECK_HOURS and reopened if Accumulate reports it delivered after all."
      },
      "additional_authorities": {
        "type": [
          "array",
          "null"
        ],
        "items": {
          "type": "string"
        },
        "description": "Transaction-header additional authorities the intent was created with; null when none."
      },
      "expires_at": {
        "type": [
          "string",
          "null"
        ],
        "description": "Transaction-header deadline (RFC 3339, whole seconds); null when the intent never expires."
      },
      "created_at": {},
      "updated_at": {},
      "completed_at": {},
      "proof": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "id": {
            "type": "string"
          },
          "bundle_url": {
            "type": [
              "string",
              "null"
            ]
          },
          "layers": {},
          "governance": {},
          "attestations": {},
          "parts": {
            "type": "object",
            "description": "Per part, what the proof service answered: `present`, `absent` (it holds none - its 404) or `unavailable` (it failed to answer; the part is null because it is not known, never because it is empty). RB4-F40.",
            "additionalProperties": false,
            "properties": {
              "layers": {
                "type": "string",
                "enum": [
                  "present",
                  "absent",
                  "unavailable"
                ]
              },
              "governance": {
                "type": "string",
                "enum": [
                  "present",
                  "absent",
                  "unavailable"
                ]
              },
              "attestations": {
                "type": "string",
                "enum": [
                  "present",
                  "absent",
                  "unavailable"
                ]
              }
            }
          },
          "unavailable": {
            "type": "array",
            "description": "Each part the proof service failed to answer for, with its HTTP status (null when it could not be reached) and reason. Empty when every part was answered.",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "part": {
                  "type": "string"
                },
                "status": {
                  "type": [
                    "integer",
                    "null"
                  ]
                },
                "reason": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "certen_transaction_list": {
    "description": "A page of transaction intents with the echoed pagination cursor.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "transactions": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "intent_id": {
              "type": "string"
            },
            "identity_id": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "intent_type": {
              "type": "string"
            },
            "accum_tx_hash": {
              "type": [
                "string",
                "null"
              ]
            },
            "proof_id": {
              "type": [
                "string",
                "null"
              ]
            },
            "proof_lookup": {
              "type": "object",
              "description": "Present when this read looked the proof id up because it was not yet recorded: `resolved` (proof_id carries it), `not_found` (not anchored yet - poll again), or `unavailable` (the proof service failed to answer, with its HTTP status, null when unreachable, and reason). A null proof_id with `unavailable` is NOT \"not anchored yet\".",
              "additionalProperties": false,
              "properties": {
                "state": {
                  "type": "string",
                  "enum": [
                    "resolved",
                    "not_found",
                    "unavailable"
                  ]
                },
                "status": {
                  "type": [
                    "integer",
                    "null"
                  ]
                },
                "reason": {
                  "type": "string"
                }
              }
            },
            "error_message": {
              "type": [
                "string",
                "null"
              ]
            },
            "reason_code": {
              "type": [
                "string",
                "null"
              ],
              "description": "Why the intent ended where it did. `target_reverted` means the destination contract rejected the call, which is a business outcome rather than a CERTEN failure. See GET /v1/transaction/{id}."
            },
            "additional_authorities": {
              "type": [
                "array",
                "null"
              ],
              "items": {
                "type": "string"
              },
              "description": "Transaction-header additional authorities the intent was created with; null when none."
            },
            "expires_at": {
              "type": [
                "string",
                "null"
              ],
              "description": "Transaction-header deadline (RFC 3339, whole seconds); null when the intent never expires."
            },
            "created_at": {},
            "updated_at": {},
            "completed_at": {}
          }
        }
      },
      "limit": {
        "type": "integer"
      },
      "offset": {
        "type": "integer"
      },
      "pagination": {
        "type": "object",
        "additionalProperties": true,
        "description": "Where this page sits. Loop until `has_more` is false — do NOT infer the end from a short page, which ends early whenever a page lands exactly on the page size.",
        "properties": {
          "limit": {
            "type": "integer",
            "description": "Page size that was applied."
          },
          "offset": {
            "type": "integer",
            "description": "Where this page started."
          },
          "has_more": {
            "type": "boolean",
            "description": "True when at least one further row exists. The only field a pager needs."
          },
          "returned": {
            "type": "integer",
            "description": "Rows in this page."
          }
        }
      }
    }
  },
  "certen_transaction_open": {
    "description": "Intent created. External mode returns signing_data + submit_url (status `signing_required`); provider mode returns the submitted tx_hash (status `submitted`); an idempotent replay echoes the original intent with `idempotent: true`.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "intent_id": {
        "type": "string"
      },
      "status": {
        "type": "string"
      },
      "signing_mode": {
        "type": "string",
        "enum": [
          "external",
          "provider"
        ]
      },
      "signing_data": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "request_id": {
            "type": "string"
          },
          "transaction_hash": {
            "type": "string"
          },
          "hash_to_sign": {
            "type": "string"
          }
        }
      },
      "submit_url": {
        "type": [
          "string",
          "null"
        ]
      },
      "tx_hash": {
        "type": [
          "string",
          "null"
        ]
      },
      "proof_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "additional_authorities": {
        "type": [
          "array",
          "null"
        ],
        "items": {
          "type": "string"
        },
        "description": "Transaction-header additional authorities the intent was created with; null when none."
      },
      "expires_at": {
        "type": [
          "string",
          "null"
        ],
        "description": "Transaction-header deadline (RFC 3339, whole seconds); null when the intent never expires."
      },
      "idempotent": {
        "type": "boolean"
      },
      "signing": {
        "type": "object",
        "additionalProperties": true
      },
      "signing_check": {
        "type": "object",
        "properties": {
          "ok": {
            "type": "boolean",
            "enum": [
              false
            ]
          },
          "code": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "details": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "required": [
          "ok",
          "code",
          "message"
        ],
        "additionalProperties": false
      }
    },
    "required": []
  },
  "certen_transaction_submit_signature": {
    "description": "Signature accepted and the signed transaction was submitted to Accumulate.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "intent_id": {
        "type": "string"
      },
      "status": {
        "type": "string"
      },
      "tx_hash": {
        "type": [
          "string",
          "null"
        ]
      }
    }
  },
  "certen_transparency_log": {
    "type": "object",
    "additionalProperties": true
  },
  "certen_transparency_price_books": {
    "type": "object",
    "additionalProperties": true
  },
  "certen_webhook_deliveries": {
    "description": "Webhook deliveries with pagination metadata.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "deliveries": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "pagination": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "limit": {
            "type": "number"
          },
          "offset": {
            "type": "number"
          },
          "total": {
            "type": "number"
          },
          "has_more": {
            "type": "boolean"
          }
        }
      }
    }
  },
  "certen_webhook_endpoints": {
    "description": "Webhook endpoints for the org.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "endpoints": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "id": {
              "type": "string"
            },
            "url": {
              "type": "string"
            },
            "event_types": {
              "type": [
                "array",
                "null"
              ],
              "items": {
                "type": "string"
              }
            },
            "description": {
              "type": [
                "string",
                "null"
              ]
            },
            "is_active": {
              "type": "boolean"
            },
            "verified_at": {
              "type": [
                "string",
                "null"
              ]
            },
            "last_success_at": {
              "type": [
                "string",
                "null"
              ]
            },
            "consecutive_failures": {
              "type": "number"
            },
            "created_at": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "certen_webhook_redeliver": {
    "description": "Delivery requeued.",
    "type": "object",
    "additionalProperties": true,
    "properties": {
      "id": {
        "type": "string"
      },
      "status": {
        "type": "string"
      }
    }
  }
};
